modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/DefaultOptions/issues"

[[mods]]
modId="defaultoptions"
version="${file.jarVersion}"
displayName="Default Options"
displayURL="https://mods.twelveiterations.com/mc/defaultoptions"
logoFile="defaultoptions-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
A way for modpacks to ship a default (key) configuration without having to include an options.txt file. Also allows local options from any mod .cfg file.
'''

[[dependencies.defaultoptions]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.defaultoptions]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.defaultoptions]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
